---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-cloud-monitoring
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 73debdbf-894f-4c14-81c7-5ece3a70b67d
    include_git_submodules: true # Including submodules in the tar package to avoid SHA validation errors during Ansible playbook execution.
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        # scc:
          # instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          # region: us-south
          # scope_resource_group_var_name: existing_resource_group_name
      - name: metrics-routing-account-settings
        mark_ready: true
        install_type: fullstack
